# Generated by Django 4.1.5 on 2023-01-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('ssn', models.IntegerField()),
                ('date_of_birth', models.IntegerField()),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.DeleteModel(
            name='User_table',
        ),
    ]
